package opendata.a00965170.comp3717.bcit.ca.database.schema;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "CATEGORIES".
 */
@Entity
public class Categories {

    @Id
    private Long id;

    @NotNull
    private String Category;

    @Generated
    public Categories() {
    }

    public Categories(Long id) {
        this.id = id;
    }

    @Generated
    public Categories(Long id, String Category) {
        this.id = id;
        this.Category = Category;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getCategory() {
        return Category;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCategory(@NotNull String Category) {
        this.Category = Category;
    }

}
