package opendata.a00965170.comp3717.bcit.ca.database.schema;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "CATEGORIES".
 */
@Entity
public class Categories {

    @Id
    private Long id;

    @NotNull
    private String category_name;
    private long category_id;

    @Generated
    public Categories() {
    }

    public Categories(Long id) {
        this.id = id;
    }

    @Generated
    public Categories(Long id, String category_name, long category_id) {
        this.id = id;
        this.category_name = category_name;
        this.category_id = category_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getCategory_name() {
        return category_name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCategory_name(@NotNull String category_name) {
        this.category_name = category_name;
    }

    public long getCategory_id() {
        return category_id;
    }

    public void setCategory_id(long category_id) {
        this.category_id = category_id;
    }

}
