package opendata.a00965170.comp3717.bcit.ca.database.schema;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DATASETS".
*/
public class DatasetsDao extends AbstractDao<Datasets, Long> {

    public static final String TABLENAME = "DATASETS";

    /**
     * Properties of entity Datasets.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "Name", false, "NAME");
        public final static Property Metadata = new Property(2, String.class, "Metadata", false, "METADATA");
        public final static Property CategoryID = new Property(3, int.class, "CategoryID", false, "CATEGORY_ID");
    }


    public DatasetsDao(DaoConfig config) {
        super(config);
    }
    
    public DatasetsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DATASETS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"NAME\" TEXT," + // 1: Name
                "\"METADATA\" TEXT," + // 2: Metadata
                "\"CATEGORY_ID\" INTEGER NOT NULL );"); // 3: CategoryID
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DATASETS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Datasets entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String Name = entity.getName();
        if (Name != null) {
            stmt.bindString(2, Name);
        }
 
        String Metadata = entity.getMetadata();
        if (Metadata != null) {
            stmt.bindString(3, Metadata);
        }
        stmt.bindLong(4, entity.getCategoryID());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Datasets entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String Name = entity.getName();
        if (Name != null) {
            stmt.bindString(2, Name);
        }
 
        String Metadata = entity.getMetadata();
        if (Metadata != null) {
            stmt.bindString(3, Metadata);
        }
        stmt.bindLong(4, entity.getCategoryID());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Datasets readEntity(Cursor cursor, int offset) {
        Datasets entity = new Datasets( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // Name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // Metadata
            cursor.getInt(offset + 3) // CategoryID
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Datasets entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setMetadata(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setCategoryID(cursor.getInt(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Datasets entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Datasets entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Datasets entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
